### ISSUE TITLE
New Rule: heavy libraries - jQuery

### ISSUE THREAD

**Issue by malwinq** [ec0lint/ec0lint#27]
### Rule details

Propose user to change jQuery dependencies to newer and lighter libraries

### What type of rule is this?

JavaScript/TypeScript code

### Which codebase the rule should be implemented?

base ec0lint

### Participation

- [ ] I am willing to submit a pull request to implement this rule.

**Comment by malwinq** [comment]
work in progress by @nemmip

**Comment by WikKam** [comment]
FYI react-dom is bigger than jquery (https://bundlephobia.com/package/react-dom@18.2.0 vs https://bundlephobia.com/package/jquery@3.6.1), I think that straight up banning some library is not the way to go

**Comment by nemmip** [comment]
Hi @WikKam I understand that according to previously implemented rules you might think, that ec0lint have only one way to achieve smth: we say: this lib might increase CO2 emission so let's ban it. But the truth is this way of working only applies to small libs, like axios, date-fns, or moment-js. We could ban jQuery just like other libs, but it's a large library and has multiple dependencies, so we've decided to split this task into more rules. Our logic is based on [this plugin](https://github.com/wikimedia/eslint-plugin-no-jquery). The approach is the same but we kinda changing the logic.
Thanks for your opinion, I agree with you, that brute force in this module is not the way to go. We will take into consideration implementing rules related with react-dom and in future we'll try to improve other rules related to heavy libraries

**Comment by WikKam** [comment]
> I understand that according to previously implemented rules you might think, that ec0lint have only one way to achieve smth: we say: this lib might increase CO2 emission so let's ban it

I think that this is stated pretty clearly here :)
<img width="636" alt="image" src="https://user-images.githubusercontent.com/52859917/199838584-89e63be1-b2fd-4413-8822-1529f75f9eb3.png">

>We could ban jQuery just like other libs, but it's a large library and has multiple dependencies

Actually JQuery has 0 dependencies (not counting devDependencies since they are not a part of what is shipped to production), as stated here: https://bundlephobia.com/package/jquery@3.6.1 and here: https://github.com/jquery/jquery/blob/main/package.json, probably you ment plugins?

I also recommend reading this excellent article with nice data for backup from Tim Kadlec, creator of https://www.webpagetest.org/ : https://timkadlec.com/remembers/2020-04-21-the-cost-of-javascript-frameworks/

"What is notable is that some frameworks correlate to better starting points than others. Sites with jQuery are the best of the bunch, starting with about 15% more JavaScript on desktop devices and about 18% more on mobile. (There’s admittedly a little bit of bias here. jQuery is found on a lot of sites, so naturally, it’s going to have a tighter relationship to the overall numbers than others. Still, that doesn’t change the way the raw numbers appear for each framework.)

While even a 15-18% increase is notable, comparing that to the opposite end of the spectrum makes the jQuery tax feel very low. Sites with Angular ship 344% more JavaScript on desktop at the 10th percentile, and 377% more on mobile. Sites with React, the next heaviest, ship 193% more JavaScript on desktop and 270% more on mobile devices."

And

"First, the unsurprising bit: when only one framework is used, performance improves far more often than not. The numbers for every framework look better at the 10th and 25th percentile. That makes sense. A site that is built well with one framework should perform better than a site that is built well with two or more.

In fact, the numbers for every framework look better at each percentile with one curious exception. What surprised me, and the reason I ended up including this data, is that at the 50th percentile and beyond, sites using React perform worse when React is the only framework in use."

Most popular modern frameworks (React, Vue, Angular) seem to be the biggest offenders and I suggest taking a look at them first :3

**Comment by malwinq** [comment]
Hi @WikKam, thank you for your comment and an interesting article
> I think that this is stated pretty clearly here :)

You're right - I used too radical mental leap. I modified it to avoid further misunderstanding.

> Most popular modern frameworks (React, Vue, Angular) seem to be the biggest offenders and I suggest taking a look at them first :3

What we want to propose to users as a suggestion is the **replacement of some of the jQuery methods (not jQuery at all) with their lighter substitute**, basing on: https://youmightnotneedjquery.com/. We actually don't focus on websites here - more on libraries, where jQuery can be imported without a second thought. Happy to take your further comments :)

In general, ec0lint can be customized by .ec0lintrc file, so if someone doesn't want to follow some of the rules, it's easy to ignore them.

**Comment by malwinq** [comment]
work in progress by @nemmip

**Comment by nemmip** [comment]
Already done rules:

- no ajax -> ban usage of ajax from jQuery
- no ajax events -> if using ajax is really necessary just juse local events instead of global ones
- no animate -> ban using animate from jQuery, prefer CSS transitions 
- no attr -> ban using attr utilities from jQuery 
- no bind -> ban using bind from jQuery 
Future implemented rules will be added soon
